### ISSUE TITLE
Dapp-encouragement does not work in Firefox

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/dapp-encouragement#29]
This is a cause of https://github.com/Agoric/agoric-sdk/issues/972

After doing the "create a project" steps, when opening http://localhost:3000/ , in the browser terminal, the following error message can be seen in Firefox:

> TypeError: URL constructor: [object Object]-bridge.html is not a valid URL.

This error does not seem to occur in Chromium-based browsers

**Comment by DavidBruant** [comment]
The error message points at this line: 

https://github.com/Agoric/dapp-encouragement/blob/68d78cf1760f45efdfd7f38110d765102579ddef/ui/public/lib/agoric-wallet.html#L24

Context:

https://github.com/Agoric/dapp-encouragement/blob/68d78cf1760f45efdfd7f38110d765102579ddef/ui/public/lib/agoric-wallet.html#L16-L24

Current hypothesis:

`\`${walletURL}-bridge.html\`` properly transforms the `ev.data` object into a string in Chrome and not in Firefox. Probably some default stringifier implemented in Chrome's DOM and not in Firefox's

**Comment by DavidBruant** [comment]
`localhost:3000` contains an iframe to `lib/agoric-wallet.html` which contains an iframe to `http://localhost:8000/wallet-bridge.html`

`/wallet-bridge.html` is the one sending the message and `lib/agoric-wallet.html` the one receiving it and reacting to it in an unexpected way (in Firefox)

`wallet-bridge.html` is defined here: https://github.com/Agoric/agoric-sdk/blob/f4f3b254d89b365875f2b054459b07fd5aff8394/packages/cosmic-swingset/lib/ag-solo/html/wallet-bridge.html

The flow of messages between iframes is a bit too complex for me to understand and get to the bottom of quickly

I'm unassigning

@michaelfig my understanding is that you're the author of most of this code, so i imagine it'll be easy for you to figure out what's going on and how to fix it

**Comment by michaelfig** [comment]
Thanks for the report and analysis.  I can test on Chrome, Safari, and Firefox, but I don't have the bandwidth for this right now.  I'll get back to it as soon as I can.

**Comment by DavidBruant** [comment]
arguably, for the very short term, it might be acceptable to tell people to use a chromium-based browser and we can focus on other things

**Comment by michaelfig** [comment]
I got this working.  It was broken under Chrome as well.
