### ISSUE TITLE
Tests currently failing with agoric-sdk master

### ISSUE THREAD

**Issue by katelynsills** [Agoric/dapp-encouragement#48]
The contract tests are currently failing, I think related to notifier changes that were made on agoric-sdk master in the past few days.

<img width="883" alt="Screen Shot 2020-07-13 at 11 19 51 AM" src="https://user-images.githubusercontent.com/2441069/87339021-d903e280-c4fa-11ea-832c-c98285c19d19.png">

**Comment by michaelfig** [comment]
Yes, looks like that.  Hoist on my own petard. 😝 

I had cleverly gotten the integration test to pass but didn't follow through with the individual contract tests.  I'll have a PR imminently.

**Comment by michaelfig** [comment]
Actually, it looks like it works for me.  The fact that it doesn't work for you seems to indicate something like an `-r esm` cache problem.

You try setting `export ESM_DISABLE_CACHE=true` to see if that fixes the failure for you.  Then, if that works, you can take the red pill and put it in your startup scripts if you want to avoid this problem entirely (until we get rid of `-r esm`).

**Comment by katelynsills** [comment]
I think my dapp-encouragement branch wasn't rebased. My apologies! This all works great.
