### ISSUE TITLE
Change `build` and `start` to use non-global parcel

### ISSUE THREAD

**Issue by bhgsbatista** [Agoric/dapp-encouragement#63]
Parcel is required for to run the demo UI, but it's not listed as a dependency.

**Comment by katelynsills** [comment]
I took a look and it appears that parcel is a local (not global) dependency (see parcel-bundler in ui/package.json), but is not getting installed. My recommendation is to do a `yarn install` in the ui folder, but @michaelfig may have intended something different with how `agoric install` works.
