### ISSUE TITLE
Update seats.md for current APIs and flows

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/dapp-encouragement#68]
`kickout(msg)` has been replaced by `fail(reason)`.
exit()` takes a completion parameter.

There's probably a bunch more.

Termination is now directed from inside the ZCF vat.

**Comment by katelynsills** [comment]
@Chris-Hibbert What is seats.md?

**Comment by Chris-Hibbert** [comment]
packages/zoe/docs/seat.md is internal documentation that talks about how zoe and zcf work together to support reallocation and exit.

**Comment by katelynsills** [comment]
Ah, is this in the wrong repo then?

**Comment by Chris-Hibbert** [comment]
Yes, this was intended to be in agoric-sdk. Thanks for noticing.
