### ISSUE TITLE
Dapp throws an error when opening up in the browser.

### ISSUE THREAD

**Issue by ski** [Agoric/dapp-encouragement#69]
Hi
I get the following error in the console when I open the home page

hmr-runtime.js:29 WebSocket connection to 'ws://127.0.0.1:36529/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
parcelRequire.../node_modules/parcel-bundler/src/builtins/hmr-runtime.js @ hmr-runtime.js:29
newRequire @ dappConstants.4000f128.js:47
(anonymous) @ dappConstants.4000f128.js:81
(anonymous) @ dappConstants.4000f128.js:120

I suspect agoric vm hasn't started up properly. I get the following when I did agoric start --reset

agoric: start: removing _agstate/agoric-servers/dev
agoric: start: initializing dev
agoric: start: setting sim chain with 0 second delay
launch-chain: Launching SwingSet kernel
web: Listening on 127.0.0.1:8000
start: swingset running
agoric: deploy: running /home/ski/agoric-sdk/packages/dapp-svelte-wallet/api/deploy.js

It seems to be stuck trying to deploy the wallet. Where can I find log files to see what may be happening? I am running Ubuntu 20 on WSL2.

**Comment by tgrecojs** [comment]
@ski what browser are you using? I recieved a similiar error in Firefox Dev & Brave. Was able to bypass by disabling the the security setting in the top right of the firefox toolbar ( i believe in private mode as well).None of this arose when I pivoted to using safari though. The logs were clear & everything worked smooth :) 






As for this:
```bash
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: initializing dev
agoric: start: setting sim chain with 0 second delay
launch-chain: Launching SwingSet kernel
web: Listening on 127.0.0.1:8000
start: swingset running
agoric: deploy: running /home/ski/agoric-sdk/packages/dapp-svelte-wallet/api/deploy.js
```
This indicates to me that my environent is working, once you execute `agoric start --reset`, you should more or less be able to forget about this `agroic start` process by navigating to a new shell where you're to run the `deploy`s yourself.

**Comment by ski** [comment]
Hi @tgrecojs 

Thanks for your response. I have tried running the dapp on Chrome, Firefox and Edge. All have the same result. The commands look fine but the app is not behaving as it should. Firstly, I can only send out a free tip. I can't do the other tip feature. I keep seeing this error that I have copied below.  
![image](https://user-images.githubusercontent.com/458710/95903288-00db3e80-0da7-11eb-962d-78a07dbbabd9.png)

Its trying to connect to a ws endpoint that is supposed to be running on port 40649 but I can't see anything running at that port. BTW, where can I find logs for things?

![image](https://user-images.githubusercontent.com/458710/95903691-9080ed00-0da7-11eb-8bae-0cbf2e139d7a.png)

Once again, thank you for your time.

**Comment by michaelfig** [comment]
Sorry for the inconvenience!

That WS endpoint is only for `parcel` to automatically refresh the dapp in development mode.  That will be fixed if you update to latest `agoric-sdk/master` and rerun `agoric install && (cd ui && yarn start)`.

I've fixed the `ackWallet` error in current `agoric-sdk/master`.  All it was doing was preventing a popup from giving you instructions (use `agoric open` to open the wallet).

> It seems to be stuck trying to deploy the wallet. Where can I find log files to see what may be happening? I am running Ubuntu 20 on WSL2.

It's probably not stuck deploying the wallet, but instead is ready for action.  We could add a message to let you know that.  You can also run `agoric start -v` (or more with `-vv`) and that will print more messages.

Please let me know if this solves it for you, then we can close the ticket.

**Comment by ski** [comment]
Thanks for your help @michaelfig , it is working now. 

> It's probably not stuck deploying the wallet, but instead is ready for action. We could add a message to let you know that. You can also run agoric start -v (or more with -vv) and that will print more messages.

Thanks for the verbose flag. Seeing outputs scrolling has a soothing effect on one even if they are errors. Let me now cobble together my own dapp and see how I do.
